version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: newrelic
    versions:
    - 7.1.0
    - 7.1.1
    - 7.1.2
    - 7.1.3
    - 7.2.0
    - 7.2.1
    - 7.3.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@bugsnag/js"
    versions:
    - 7.6.0
    - 7.7.0
    - 7.8.0
    - 7.9.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
